version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    build: ./rabbitmq-docker
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
  websockets-app:
    build: ./kafka-websockets
    ports:
      - "8080-8082:8080"
  websockets-webapp:
    build: ./kafka-websockets-webapp
    ports:
      - "4200:4200"
